### ISSUE TITLE
Undoing threads leaves objects behind

### ISSUE THREAD

**Issue by pierreporte** [martinproks/cosmeticthread3d#35]
How to reproduce:

1. Create a thread on a part (Part or PartDesign, doesn’t matter).
2. Undo it (it takes several clicks).
3. The tree still contain two objects: ThreadOrientation and CosmeticThread3DExternal or CosmeticThread3DInternal.

There should be nothing left in the tree.

ThreadOrientation shouldn’t be in the tree in the first place.

**Comment by martinproks** [comment]
Hi,
Test it please. It should be fixed now - commit #52.

**Comment by pierreporte** [comment]
The problem still exist but a bit different.

Complete model:
![image](https://github.com/martinproks/cosmeticthread3d/assets/2029853/625737ac-338f-4c57-812a-a0cd87308a90)

1st undo:
![image](https://github.com/martinproks/cosmeticthread3d/assets/2029853/537b1698-c56b-4805-a981-68d2c4f8223a)

2nd undo:
![image](https://github.com/martinproks/cosmeticthread3d/assets/2029853/cb7bec21-ff87-465e-8963-45a5642f4bfd)

3rd undo:
![image](https://github.com/martinproks/cosmeticthread3d/assets/2029853/e3d0325b-6451-407b-9b4a-d264fe5bd505)

The desired result is achieved by the 3rd undo.

BTW the new implementation with common a Part & PartDesign feature doesn’t put the threads in the Boly container.

**Comment by martinproks** [comment]
Hi,

Problem 1 - undo.
I think this is OK - it is safe solution without hidden side effects.
If I change it to one step, there will be another possible risk/issue related to undo system in FreeCAD. The undo is not handling just on one document, but on whole FreeCAD (according to documentation). If I open undo trigger at the begin of the thread command and close it at the end, it will be undo at one step. But there are 2 non modal dialogs (attachment editor and thread UI). User can switch document to other, change something, go back to the document with ct3d and finish thread (dialogs). Less probable, but possible. And when the user hit undo, it will undo all actions in all documents between ct3d start and finish in one undo. Instead of multiple undo steps in multiple documents...

About Part Design. The PartDesign version is suppressed. There is just Part version accessible. [Read user manual](http://htmlpreview.github.io/?https://github.com/martinproks/cosmeticthread3d/blob/main/doc/user-manual.html#PartPartDesign_ct3d)

**Comment by pierreporte** [comment]
Got it. It’s a nasty side effect of https://github.com/FreeCAD/FreeCAD/issues/11914.
